# Описание проекта:

# Импорт библиотек

In [1]:
!pip install shap -q
!pip install phik -q
!pip install -Uq scikit-learn
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.2.6)
Requirement already satisfied: pandas>=1.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

<b>Проверка версии sklearn</b>

In [2]:
import sklearn
sklearn.__version__

'1.7.2'

In [3]:
# Импорт библиотек для работы с данными
import pandas as pd
import numpy as np

# Импорт библиотек для визуализации
import matplotlib.pyplot as plt
import seaborn as sns
import phik
import shap

# Импорт библиотек для создания модели

pd.set_option('display.max_columns', None)

C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1. Загрузка данных

### 1.1 Создание датафреймов

In [4]:
# Тренировочные данные
train_df = pd.read_csv('heart_train.csv')
# Тестовые данные
test_df = pd.read_csv('heart_test.csv')

print('Тренировочная выборка:')
display(train_df.head(5))
print('Тестовая выборка:')
display(test_df.head(5))

Тренировочная выборка:

,Unnamed: 0,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk (Binary),Blood sugar,CK-MB,Troponin,Gender,Systolic blood pressure,Diastolic blood pressure,id
0,0,0.359551,0.732143,0.074244,1.0,1.0,1.0,1.0,1.0,0.535505,1,1.0,0.0,8.0,0.225704,0.105948,0.459176,0.979221,3.0,0.333333,0.0,0.227018,0.048229,0.036512,Male,0.212903,0.709302,2664
1,1,0.202247,0.325000,0.047663,1.0,1.0,0.0,0.0,1.0,0.068690,2,1.0,0.0,9.0,0.289923,0.164217,0.117053,0.515584,3.0,0.833333,0.0,0.150198,0.017616,0.000194,Female,0.412903,0.569767,9287
2,2,0.606742,0.860714,0.055912,1.0,0.0,1.0,1.0,1.0,0.944001,2,1.0,1.0,6.0,0.550133,0.598745,0.373574,0.012987,2.0,1.000000,0.0,0.227018,0.048229,0.036512,Female,0.238710,0.220930,5379
3,3,0.730337,0.007143,0.053162,0.0,0.0,1.0,0.0,1.0,0.697023,0,0.0,1.0,3.0,0.330962,0.077605,0.049735,0.131169,0.0,0.333333,1.0,0.227018,0.048229,0.036512,Female,0.348387,0.267442,8222
4,4,0.775281,0.757143,0.021998,0.0,0.0,1.0,0.0,1.0,0.412878,1,0.0,0.0,8.0,0.524600,0.341960,0.830405,0.070130,5.0,1.000000,1.0,0.227018,0.048229,0.036512,Male,0.619355,0.441860,4047

Тестовая выборка:

,Unnamed: 0,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Blood sugar,CK-MB,Troponin,Gender,Systolic blood pressure,Diastolic blood pressure,id
0,0,0.494382,0.264286,0.062328,0.0,1.0,1.0,1.0,1.0,0.361618,2,0.0,0.0,8.0,0.194370,0.587759,0.283490,0.306494,1.0,0.333333,0.227018,0.048229,0.036512,Male,0.283871,0.372093,7746
1,1,0.224719,0.953571,0.082493,1.0,0.0,0.0,1.0,0.0,0.996483,2,1.0,1.0,5.0,0.329888,0.602883,0.467036,0.087013,0.0,0.166667,0.227018,0.048229,0.036512,Female,0.703226,0.441860,4202
2,2,0.629213,0.092857,0.064161,0.0,1.0,1.0,1.0,0.0,0.995561,0,0.0,0.0,10.0,0.780075,0.370436,0.409366,0.205195,7.0,1.000000,0.102767,0.002666,0.088455,Male,0.458065,0.779070,6632
3,3,0.460674,0.567857,0.055912,1.0,1.0,1.0,1.0,1.0,0.437277,0,0.0,0.0,10.0,0.785071,0.368242,0.910261,0.163636,0.0,0.666667,0.203557,0.056390,0.271774,Female,0.741935,0.255814,4639
4,4,0.719101,0.485714,0.022915,1.0,0.0,1.0,0.0,1.0,0.514920,0,0.0,0.0,7.0,0.070919,0.729578,0.758924,0.580519,5.0,0.000000,0.227018,0.048229,0.036512,Male,0.412903,0.395349,4825

### 1.2 Первичный анализ

In [5]:
def primary_analysis(df):
    df.info()
    display(df.describe())
    return ''

In [6]:
print('Тренировочная выборка:')
print(primary_analysis(train_df), '\n', train_df.shape)
print('Тестовая выборка:')
print(primary_analysis(test_df), '\n', test_df.shape)

Тренировочная выборка:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8685 entries, 0 to 8684
Data columns (total 28 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       8685 non-null   int64
 1   Age                              8685 non-null   float64
 2   Cholesterol                      8685 non-null   float64
 3   Heart rate                       8685 non-null   float64
 4   Diabetes                         8442 non-null   float64
 5   Family History                   8442 non-null   float64
 6   Smoking                          8442 non-null   float64
 7   Obesity                          8442 non-null   float64
 8   Alcohol Consumption              8442 non-null   float64
 9   Exercise Hours Per Week          8685 non-null   float64
 10  Diet                             8685 non-null   int64
 11  Previous Heart Problems          8442 non-null   float64
 12  Medication Use                   8442 non-null   float64
 13  Stress Level                     8442 non-null   float64
 14  Sedentary Hours Per Day          8685 non-null   float64
 15  Income                           8685 non-null   float64
 16  BMI                              8685 non-null   float64
 17  Triglycerides                    8685 non-null   float64
 18  Physical Activity Days Per Week  8442 non-null   float64
 19  Sleep Hours Per Day              8685 non-null   float64
 20  Heart Attack Risk (Binary)       8685 non-null   float64
 21  Blood sugar                      8685 non-null   float64
 22  CK-MB                            8685 non-null   float64
 23  Troponin                         8685 non-null   float64
 24  Gender                           8685 non-null   object
 25  Systolic blood pressure          8685 non-null   float64
 26  Diastolic blood pressure         8685 non-null   float64
 27  id                               8685 non-null   int64
dtypes: float64(24), int64(3), object(1)
memory usage: 1.9+ MB

,Unnamed: 0,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk (Binary),Blood sugar,CK-MB,Troponin,Systolic blood pressure,Diastolic blood pressure,id
count,8685.000000,8685.000000,8685.000000,8685.000000,8442.000000,8442.000000,8442.000000,8442.000000,8442.000000,8685.000000,8685.000000,8442.000000,8442.000000,8442.000000,8685.000000,8685.000000,8685.000000,8685.000000,8442.000000,8685.000000,8685.000000,8685.000000,8685.000000,8685.000000,8685.000000,8685.000000,8685.000000
mean,4342.000000,0.449958,0.501070,0.050658,0.652097,0.489576,0.902867,0.498342,0.601990,0.503378,1.057455,0.495380,0.501185,5.493367,0.499164,0.496055,0.496774,0.505484,3.508292,0.503737,0.346920,0.227339,0.048159,0.036689,0.450295,0.497634,4831.210823
std,2507.287877,0.231174,0.284716,0.023453,0.476333,0.499921,0.296157,0.500027,0.489517,0.284810,0.866645,0.500008,0.500028,2.867862,0.285340,0.284698,0.282561,0.286320,2.281772,0.328061,0.476017,0.076635,0.075531,0.060157,0.170184,0.171830,2782.585625
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2171.000000,0.258427,0.267857,0.034830,0.000000,0.000000,1.000000,0.000000,0.000000,0.263286,0.000000,0.000000,0.000000,3.000000,0.255875,0.251922,0.254190,0.263636,2.000000,0.166667,0.000000,0.227018,0.048229,0.036512,0.303226,0.348837,2425.000000
50%,4342.000000,0.460674,0.499780,0.050412,1.000000,0.000000,1.000000,0.000000,1.000000,0.502110,1.000000,0.000000,1.000000,5.000000,0.499920,0.494889,0.494774,0.503603,3.000000,0.500000,0.000000,0.227018,0.048229,0.036512,0.445161,0.500000,4837.000000
75%,6513.000000,0.640449,0.746429,0.065995,1.000000,1.000000,1.000000,1.000000,1.000000,0.748709,2.000000,1.000000,1.000000,8.000000,0.744623,0.741036,0.736974,0.750649,6.000000,0.833333,1.000000,0.227018,0.048229,0.036512,0.600000,0.651163,7242.000000
max,8684.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,10.000000,1.000000,1.000000,1.000000,1.000000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9650.000000

 (8685, 28)
Тестовая выборка:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 966 entries, 0 to 965
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Unnamed: 0                       966 non-null    int64
 1   Age                              966 non-null    float64
 2   Cholesterol                      966 non-null    float64
 3   Heart rate                       966 non-null    float64
 4   Diabetes                         935 non-null    float64
 5   Family History                   935 non-null    float64
 6   Smoking                          935 non-null    float64
 7   Obesity                          935 non-null    float64
 8   Alcohol Consumption              935 non-null    float64
 9   Exercise Hours Per Week          966 non-null    float64
 10  Diet                             966 non-null    int64
 11  Previous Heart Problems          935 non-null    float64
 12  Medication Use                   935 non-null    float64
 13  Stress Level                     935 non-null    float64
 14  Sedentary Hours Per Day          966 non-null    float64
 15  Income                           966 non-null    float64
 16  BMI                              966 non-null    float64
 17  Triglycerides                    966 non-null    float64
 18  Physical Activity Days Per Week  935 non-null    float64
 19  Sleep Hours Per Day              966 non-null    float64
 20  Blood sugar                      966 non-null    float64
 21  CK-MB                            966 non-null    float64
 22  Troponin                         966 non-null    float64
 23  Gender                           966 non-null    object
 24  Systolic blood pressure          966 non-null    float64
 25  Diastolic blood pressure         966 non-null    float64
 26  id                               966 non-null    int64
dtypes: float64(23), int64(3), object(1)
memory usage: 203.9+ KB

,Unnamed: 0,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Blood sugar,CK-MB,Troponin,Systolic blood pressure,Diastolic blood pressure,id
count,966.00000,966.000000,966.000000,966.000000,935.000000,935.000000,935.000000,935.000000,935.000000,966.000000,966.000000,935.000000,935.000000,935.000000,966.000000,966.000000,966.000000,966.000000,935.000000,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000,966.000000
mean,482.50000,0.452916,0.488181,0.051644,0.656684,0.481283,0.898396,0.516578,0.583957,0.490706,1.053830,0.494118,0.488770,5.332620,0.506715,0.484408,0.476796,0.486688,3.443850,0.512571,0.224127,0.048855,0.034926,0.447172,0.496822,4769.160455
std,279.00448,0.231068,0.282039,0.035502,0.475070,0.499917,0.302289,0.499993,0.493165,0.284902,0.884642,0.500233,0.500141,2.858466,0.287826,0.273879,0.291987,0.284534,2.302778,0.322292,0.065270,0.079742,0.053855,0.171837,0.173935,2818.815407
min,0.00000,0.044944,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000336,0.000000,0.000000,0.000000,1.000000,0.001187,0.003351,0.002598,0.000000,0.000000,0.000000,0.029644,0.000000,0.000194,0.012903,0.116279,0.000000
25%,241.25000,0.247191,0.243750,0.036664,0.000000,0.000000,1.000000,0.000000,0.000000,0.243431,0.000000,0.000000,0.000000,3.000000,0.258713,0.261446,0.217527,0.249675,1.000000,0.166667,0.227018,0.048229,0.036512,0.296774,0.348837,2275.750000
50%,482.50000,0.460674,0.499780,0.050412,1.000000,0.000000,1.000000,1.000000,1.000000,0.502110,1.000000,0.000000,0.000000,5.000000,0.501327,0.492015,0.471185,0.488961,3.000000,0.500000,0.227018,0.048229,0.036512,0.445161,0.488372,4769.500000
75%,723.75000,0.640449,0.710714,0.065995,1.000000,1.000000,1.000000,1.000000,1.000000,0.734425,2.000000,1.000000,1.000000,8.000000,0.759591,0.705371,0.720503,0.718182,5.000000,0.833333,0.227018,0.048229,0.036512,0.600000,0.639535,7206.000000
max,965.00000,0.853933,0.996429,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.998938,3.000000,1.000000,1.000000,10.000000,0.999033,0.998885,0.999496,0.998701,7.000000,1.000000,0.750988,1.000000,0.970871,0.741935,0.790698,9644.000000

 (966, 27)

### 1.3 Вывод по первичному анализу

## 2. Предобработка данных

### 2.1 Поиск дубликатов

In [7]:
train_df.duplicated().sum()

np.int64(0)

### 2.2 Работа с пропусками

In [8]:
train_df.isna().sum()

Unnamed: 0                           0
Age                                  0
Cholesterol                          0
Heart rate                           0
Diabetes                           243
Family History                     243
Smoking                            243
Obesity                            243
Alcohol Consumption                243
Exercise Hours Per Week              0
Diet                                 0
Previous Heart Problems            243
Medication Use                     243
Stress Level                       243
Sedentary Hours Per Day              0
Income                               0
BMI                                  0
Triglycerides                        0
Physical Activity Days Per Week    243
Sleep Hours Per Day                  0
Heart Attack Risk (Binary)           0
Blood sugar                          0
CK-MB                                0
Troponin                             0
Gender                               0
Systolic blood pressure              0
Diastolic blood pressure             0
id                                   0
dtype: int64

### 2.3 Проверка типов данных

In [9]:
train_df.dtypes

Unnamed: 0                           int64
Age                                float64
Cholesterol                        float64
Heart rate                         float64
Diabetes                           float64
Family History                     float64
Smoking                            float64
Obesity                            float64
Alcohol Consumption                float64
Exercise Hours Per Week            float64
Diet                                 int64
Previous Heart Problems            float64
Medication Use                     float64
Stress Level                       float64
Sedentary Hours Per Day            float64
Income                             float64
BMI                                float64
Triglycerides                      float64
Physical Activity Days Per Week    float64
Sleep Hours Per Day                float64
Heart Attack Risk (Binary)         float64
Blood sugar                        float64
CK-MB                              float64
Troponin                           float64
Gender                              object
Systolic blood pressure            float64
Diastolic blood pressure           float64
id                                   int64
dtype: object

In [10]:
train_df['Gender'].value_counts()

Gender
Male      5882
Female    2560
1.0        156
0.0         87
Name: count, dtype: int64

<b>Видим странные значения в гендере. По соотношению можно предположить, что 1.0 - это Male, а 0.0 - это Female</b>

In [11]:
train_df['Gender'] = train_df['Gender'].replace({'1.0': 'Male', '0.0': 'Female'})
# Дополнительная проверка
train_df['Gender'].value_counts()

Gender
Male      6038
Female    2647
Name: count, dtype: int64

In [12]:
def change_type_df(df, list_change):
    for i in list_change:
        # Конвертируем в numeric (строки/нечисла -> NaN)
        df[i] = pd.to_numeric(df[i], errors='coerce')
        df[i] = df[i].astype('Int32')
        print(f'Тип признака {i} был изменен на {df[i].dtype}')
    return df.head(15)

In [13]:
list_change = ['Heart Attack Risk (Binary)', 
               'Diabetes', 
               'Family History', 
               'Smoking', 
               'Obesity', 
               'Alcohol Consumption', 
               'Previous Heart Problems', 
               'Medication Use', 
               'Stress Level', 
               'Physical Activity Days Per Week',]

In [14]:
change_type_df(train_df, list_change)

Тип признака Heart Attack Risk (Binary) был изменен на Int32
Тип признака Diabetes был изменен на Int32
Тип признака Family History был изменен на Int32
Тип признака Smoking был изменен на Int32
Тип признака Obesity был изменен на Int32
Тип признака Alcohol Consumption был изменен на Int32
Тип признака Previous Heart Problems был изменен на Int32
Тип признака Medication Use был изменен на Int32
Тип признака Stress Level был изменен на Int32
Тип признака Physical Activity Days Per Week был изменен на Int32

,Unnamed: 0,Age,Cholesterol,Heart rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Diet,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk (Binary),Blood sugar,CK-MB,Troponin,Gender,Systolic blood pressure,Diastolic blood pressure,id
0,0,0.359551,0.732143,0.074244,1,1,1,1,1,0.535505,1,1,0,8,0.225704,0.105948,0.459176,0.979221,3,0.333333,0,0.227018,0.048229,0.036512,Male,0.212903,0.709302,2664
1,1,0.202247,0.325000,0.047663,1,1,0,0,1,0.068690,2,1,0,9,0.289923,0.164217,0.117053,0.515584,3,0.833333,0,0.150198,0.017616,0.000194,Female,0.412903,0.569767,9287
2,2,0.606742,0.860714,0.055912,1,0,1,1,1,0.944001,2,1,1,6,0.550133,0.598745,0.373574,0.012987,2,1.000000,0,0.227018,0.048229,0.036512,Female,0.238710,0.220930,5379
3,3,0.730337,0.007143,0.053162,0,0,1,0,1,0.697023,0,0,1,3,0.330962,0.077605,0.049735,0.131169,0,0.333333,1,0.227018,0.048229,0.036512,Female,0.348387,0.267442,8222
4,4,0.775281,0.757143,0.021998,0,0,1,0,1,0.412878,1,0,0,8,0.524600,0.341960,0.830405,0.070130,5,1.000000,1,0.227018,0.048229,0.036512,Male,0.619355,0.441860,4047
5,5,0.168539,0.764286,0.057745,0,1,1,1,1,0.082682,1,1,0,7,0.558262,0.640836,0.110571,0.238961,6,0.833333,0,0.227018,0.048229,0.036512,Male,0.464516,0.418605,5817
6,6,0.483146,0.021429,0.036664,1,0,1,0,1,0.540206,2,0,1,9,0.827611,0.774609,0.073718,0.072727,5,0.000000,1,0.231225,0.008940,0.000291,Male,0.361290,0.569767,5580
7,7,0.235955,0.939286,0.081577,1,0,1,0,1,0.290837,2,0,1,7,0.225275,0.999364,0.001534,0.180519,4,0.000000,0,0.227018,0.048229,0.036512,Male,0.690323,0.639535,4963
8,8,0.685393,0.317857,0.039413,0,0,1,0,0,0.803160,0,1,1,3,0.828176,0.142208,0.093073,0.990909,6,0.166667,1,0.126482,0.002332,0.007185,Male,0.664516,0.616279,4521
9,9,0.213483,0.796429,0.076994,1,1,1,1,0,0.506971,1,0,0,7,0.692973,0.820952,0.145447,0.171429,3,1.000000,0,0.227018,0.048229,0.036512,Male,0.651613,0.720930,2455
10,10,0.651685,0.471429,0.021998,1,1,1,1,1,0.885421,0,1,0,7,0.072585,0.785860,0.419197,0.027273,5,0.333333,0,0.227018,0.048229,0.036512,Male,0.593548,0.686047,1090
11,11,0.808989,0.878571,0.054079,1,0,1,0,0,0.642113,1,0,0,1,0.389096,0.563285,0.331737,0.514286,7,0.000000,1,0.227018,0.048229,0.036512,Male,0.664516,0.790698,5062
12,12,0.179775,0.614286,0.051329,1,1,1,0,0,0.304094,2,0,0,9,0.181218,0.740618,0.462179,0.288312,6,1.000000,0,0.227018,0.048229,0.036512,Male,0.548387,0.767442,4709
13,13,0.797753,0.017857,0.060495,0,1,1,1,0,0.417687,1,1,0,8,0.381124,0.048229,0.829837,0.353247,5,0.666667,0,0.227018,0.048229,0.036512,Female,0.503226,0.755814,9293
14,14,0.337079,0.750000,0.059578,1,1,1,0,1,0.832090,1,1,0,10,0.268019,0.357602,0.173063,0.098701,7,0.833333,0,0.310277,0.003834,0.004661,Male,0.161290,0.232558,747

### 2.4 Вывод по предобработке данных

In [15]:
while True:
    asdasd

NameError: name 'asdasd' is not defined

## 3. Исследование данных

### 3.1 Создание списков для разных величин

In [ ]:
# Список для создания графиков countplot (категориальные и дискретные переменные с низким числом уникальных значений)
bar_cols = [
    'Gender',
    'Diabetes',
    'Family History',
    'Smoking',
    'Obesity',
    'Alcohol Consumption',
    'Diet',
    'Previous Heart Problems',
    'Medication Use',
    'Stress Level',
    'Physical Activity Days Per Week',
    'Heart Attack Risk (Binary)'
]

# Список для создания коробчатой диаграммы и графиком распределения данных (непрерывные переменные)
continuous_cols = [
    'Age',
    'Cholesterol',
    'Heart rate',
    'Exercise Hours Per Week',
    'Sedentary Hours Per Day',
    'Income',
    'BMI',
    'Triglycerides',
    'Sleep Hours Per Day',
    'Blood sugar',
    'CK-MB',
    'Troponin',
    'Systolic blood pressure',
    'Diastolic blood pressure'
]

# Список для создание круговой диаграммы (переменные с пропорциональными категориями, подходящими для показа долей, напр. бинарные)
equal_cols = [
    'Gender',
    'Heart Attack Risk (Binary)'
]

<b>3.2 Установка настроек для красивых графиков</b>

In [ ]:
sns.set_theme(style="whitegrid", palette="husl", font_scale=1.1)
plt.rcParams['figure.figsize'] = (12, 8)  # Размер фигур по умолчанию
plt.rcParams['axes.titlesize'] = 16
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

In [ ]:
fig, axes = plt.subplots(4, 3, figsize=(18, 16))
axes = axes.ravel()  # Разворачиваем в 1D для удобства

for i, col in enumerate(bar_cols):
    if i < len(axes):  # На случай, если меньше подграфиков
        sns.countplot(data=train_df, x=col, hue=col, ax=axes[i], palette='husl', legend=False)
        axes[i].set_title(f'Распределение: {col}', fontweight='bold')
        axes[i].tick_params(axis='x', rotation=45 if len(train_df[col].unique()) > 5 else 0)
        for container in axes[i].containers:
            axes[i].bar_label(container, fmt='%.0f')  # Добавляем значения на бары

plt.tight_layout()
plt.suptitle('Countplots для категориальных переменных', y=1.02, fontsize=18, fontweight='bold')
plt.show()

In [ ]:
fig, axes = plt.subplots(4, 4, figsize=(20, 16))
axes = axes.ravel()

for i, col in enumerate(continuous_cols):
    if i < len(axes):
        # Boxplot без palette (чтобы избежать предупреждения; используем color для единого цвета)
        sns.boxplot(data=train_df, y=col, ax=axes[i], color='lightblue')
        axes[i].set_title(f'Boxplot: {col}', fontweight='bold')
        axes[i].tick_params(axis='y', rotation=0)

plt.tight_layout()
plt.suptitle('Boxplots для непрерывных переменных', y=1.02, fontsize=18, fontweight='bold')
plt.show()

In [ ]:
fig, axes = plt.subplots(4, 4, figsize=(20, 16))
axes = axes.ravel()

for i, col in enumerate(continuous_cols):
    if i < len(axes):
        # Histplot без palette (чтобы избежать предупреждения; цвет по умолчанию или через color)
        sns.histplot(data=train_df, x=col, kde=True, ax=axes[i], bins=30, alpha=0.7, color='skyblue')
        axes[i].set_title(f'Распределение: {col}', fontweight='bold')
        axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.suptitle('Гистограммы распределений для непрерывных переменных', y=1.02, fontsize=18, fontweight='bold')
plt.show()

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

for i, col in enumerate(equal_cols):
    if i < len(axes):
        value_counts = train_df[col].value_counts()
        axes[i].pie(value_counts.values, labels=value_counts.index.astype(str), autopct='%1.1f%%',
                    colors=sns.color_palette('husl', len(value_counts)), startangle=90, textprops={'fontsize': 12})
        axes[i].set_title(f'Доли: {col}', fontweight='bold', fontsize=14)

plt.suptitle('Круговые диаграммы для пропорциональных категорий', y=1.02, fontsize=18, fontweight='bold')
plt.tight_layout()
plt.show()

## 4. Корреляционный анализ

In [ ]:
phik_corr = train_df.drop(columns='id', axis=1).phik_matrix()
plt.figure(figsize=(15, 12))
sns.heatmap(phik_corr, annot=True, cmap='coolwarm', vmin=0, vmax=1)
plt.title('Phik корреляционная матрица');

## 5. Использование пайплайнов